on: [push]
name: tests
jobs:
  runhaskell:
    name: Run tests
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4.8'
          cabal-version: '3.0.0.0'
      - run: cabal run lits-test
